# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_Text', models.TextField()),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=200)),
                ('Post_Text', models.TextField()),
                ('Post_DatePub', models.DateTimeField()),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_NickName', models.CharField(max_length=200)),
                ('User_FIO', models.CharField(max_length=200)),
                ('User_DateReg', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_7_DjangoModels.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Post_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_7_DjangoModels.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_7_DjangoModels.User'),
        ),
    ]
